spring.application.name=NEW-PSA

#Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/git
spring.datasource.username=root
spring.datasource.password=dbms123
spring.jpa.hibernate.ddl-auto=update
